### ISSUE TITLE
Release version jai-imageio-1.2-pre-dr-b04-2011-07-04

### ISSUE THREAD

**Issue by 4F2E4A2E** [jai-imageio/jai-imageio-core#12]
Hello there! Thanks for creating and releasing this lib to maven central, it is a great help!

The Tess4J project would appreciate it very much if we could release some minor versions of jai-imageio from this repo like jai-imageio-1.2-pre-dr-b04-2011-07-04 to maven central that we are using to build.

I could do it myself, but have not rights in this repo. Please get back to me on this. I would create a branch from that tag, and release and then perform.

Thanks in advance!

**Comment by stain** [comment]
jai-imageio-core is already [released to Maven Central](http://central.maven.org/maven2/com/github/jai-imageio/jai-imageio-core/). 


See https://github.com/jai-imageio/jai-imageio-core#usage - in short:

```
<dependency>
    <groupId>com.github.jai-imageio</groupId>
    <artifactId>jai-imageio-core</artifactId>
    <version>1.3.0</version>
</dependency>
```

Note that version 1.3.0 changes package name to `com.github.jaiimageio` - if you need the older reserved package name `com.sun.media.imageio.stream`, use version 1.2.1
