### ISSUE TITLE
Release jai-imageio-core 1.3.1

### ISSUE THREAD

**Issue by stain** [jai-imageio/jai-imageio-core#17]
I think it's time for a new release. I have updated the release notes to include the TIFF memory fix and OSGi bundle. Thanks to the new contributors!

(BTW: I have also invited all contributors to be owners/committers of this github organization)

I guess version 1.3.1 is OK, even though we are now an OSGi bundle?

Anything else that needs to be updated before the release? I will prepare a release candidate.

**Comment by stain** [comment]
Trying an Apache-style release candidate.

Please vote over the release candidate jai-imageio-core-1.3.1-RC1

+1 : Release jai-imageio-core-1.3.1-RC1
+0: No opinion
-1: Don't release, because..

Anyone can vote! Simply reply to this message.

The release will pass if a majority of votes have been received within 2015-10-08 (1 week).

Commit: https://github.com/jai-imageio/jai-imageio-core/commit/69c0e2f32fa006f77b653a260744bd8d60cf1707

Tag: https://github.com/jai-imageio/jai-imageio-core/tree/jai-imageio-core-1.3.1-RC1

Binaries: https://bintray.com/stain/maven/jai-imageio-core-release-candidates/1.3.1/view#files

Maven repository: http://dl.bintray.com/stain/maven/
aka http://dl.bintray.com/stain/maven/com/github/jai-imageio/jai-imageio-core/1.3.1/

Binaries are signed with PGP key A0FFD119

To test with Maven, use:

```xml
<dependencies>
    <dependency>
        <groupId>com.github.jai-imageio</groupId>
        <artifactId>jai-imageio-core</artifactId>
        <version>1.3.1</version>
    </dependency>
</dependencies>
<repositories>
<repository>
<snapshots>
<enabled>false</enabled>
</snapshots>
<id>bintray-stain-maven</id>
<name>bintray</name>
<url>http://dl.bintray.com/stain/maven</url>
</repository>
</repositories>
```

If the release candidate is approved, I will publish to Maven Central and change the tag to jai-imageio-core-1.3.1.

**Comment by seanjreilly** [comment]
A belated +1!

**Comment by stain** [comment]
Thanks, @seanjreilly!

Now 1.3.1 has been tagged, released, etc.. should appear in [Maven Central](http://central.maven.org/maven2/com/github/jai-imageio/jai-imageio-core/) in a few hours - for the inpatient see https://bintray.com/jai-imageio/maven/jai-imageio-core-standalone
