### ISSUE TITLE
README should suggest using https to download library

### ISSUE THREAD

**Issue by benmccann** [jai-imageio/jai-imageio-core#18]
This line:

    <url>http://dl.bintray.com/jai-imageio/maven/</url>

Should be changed to:

    <url>https://dl.bintray.com/jai-imageio/maven/</url>

To read more details about the risks of using http to download software, please see here: http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/

**Comment by stain** [comment]
Thanks. Also added https link to GitHub releases and Maven Central folder.
