### ISSUE TITLE
Why the name JAI?

### ISSUE THREAD

**Issue by leolux** [jai-imageio/jai-imageio-core#21]
How would you describe the relation between jai-imageio-core and Java Advanced Imaging API (JAI)? Should it be a replacement, alternative, extension, wrapper or something different?

**Comment by stain** [comment]
This is a fork of [jai-imageio-core](https://java.net/projects/jai-imageio-core/) from java.net - but removing certain non-opensource or binary component that were present there. It's a module for JAI.
