### ISSUE TITLE
empty string when call ImageIO.getReaderMIMETypes()

### ISSUE THREAD

**Issue by CarolWu1206** [jai-imageio/jai-imageio-core#27]
When jai-imageio-core is not included, the result for ImageIO.getReaderMIMETypes() is 
"image/png","image/vnd.wap.wbmp","image/x-png","image/jpeg","image/bmp","image/gif".

After employing the package, the result is 
"","image/png","image/vnd.wap.wbmp","image/jpeg","image/x-portable-graymap","image/bmp","image/pcx","image/x-windows-bmp","image/gif","image/x-windows-pcx","image/x-pc-paintbrush","image/x-bmp","image/x-pcx","image/x-png","image/x-portable-bitmap","image/x-portable-pixmap","image/tiff","image/x-portable-anymap".

The empty string in the head causes error, is it possible to remove such a string?

**Comment by stain** [comment]
Thanks! The empty string seems to come from `com.github.jaiimageio.impl.plugins.raw.RawImageReaderSpi`

which has weirdly specified:

    private static String[] entensions = {""};
    private static String[] mimeType = {""};

i don't know which of the [many "raw" formats](https://en.wikipedia.org/wiki/Raw_image_format) this means, so I've changed those to extension `raw` and mimetype `image/x-raw` in `RawImageReaderSpi` and `RawImageWriterSpi`
