### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by Jugen** [jai-imageio/jai-imageio-core#49]
Its been more than two years since the last release, and there have been some changes pertinent to Java 9, so could we please have a new release.

**Comment by pejobo** [comment]
@stain Anything holding back a release?

**Comment by stain** [comment]
Hi, sorry about the delay, I promised I would get it done over Easter holiday - turns out family is quite demanding even when supplied with chocolate! Will have another go this week.

**Comment by Jugen** [comment]
Family is more important, so no worries (Hope you had a good time :-). 
And thanks for getting back to us .....

**Comment by stain** [comment]
As I merged #41 with Java 9 support (which needs newer Maven and Java 1.6 to compile) I'll bump to 1.4.0 instead of 1.3.2 to follow https://semver.org/ rules.

Updating README now.

**Comment by stain** [comment]
- [x] Update README contributors
- [x] Invite new contributors to github org
- [ ] Update README changelog
- [x] Ensure Travis is [happy] again
- [ ] Generate/publish new javadoc
- [ ] `mvn release:prepare` (version bump, tag, test)
- [ ] `mvn release:run` (deploy to [bintray repository](https://dl.bintray.com/jai-imageio/maven/))
- [ ] Push from bintray to Maven Central
- [ ] Tweet about it? :)
- [ ] Wait for firestorm about not actually working in Java 9..

**Comment by stain** [comment]
jai-imageio [1.4.0 Release Candidate 1](https://github.com/jai-imageio/jai-imageio-core/releases/tag/jai-imageio-core-1.4.0) available now in [bintray](https://dl.bintray.com/jai-imageio/maven/com/github/jai-imageio/jai-imageio-core/1.4.0/).

Could I have anyone testing it (say in a real application) before I push it to Maven Central? Particularly interested in Java 9 testers.

**Comment by ansell** [comment]
In my case, excluding ``javax.media:jai-imageio:1.1`` that GeoTools-19.0 pulls in through its dependencies, and replacing it with this release, fixed a bug I was having on initialisation of the image io classes on Java-9, and doesn't seem to have generated any further issues.

For anyone finding the same issue, pasting the error here may help them:

```
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.sun.media.imageioimpl.common.ImageUtil.processOnRegistration(ImageUtil.java:1408)
	at com.sun.media.imageioimpl.plugins.bmp.BMPImageWriterSpi.onRegistration(BMPImageWriterSpi.java:107)
	at java.desktop/javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:788)
	at java.desktop/javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:330)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:212)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:136)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:157)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
```

Having said that, as far as I am aware I am only writing out to PNG, which has its writer provider implemented by the JDK, so unless GeoTools-19.0 are using the other ImageIO providers internally I don't think I am testing its functionality fully myself.

Compiling this release using Java-9 worked for me with no warnings or errors with unit tests or compilation. There are a large number of javadoc warnings although not sure how many exactly as the javadoc processor may have stopped counting at 99.

**Comment by JamzTheMan** [comment]
Awesome! I will test it as soon as I can this week.  I mostly use it to access jpeg2000.

**Comment by mykolap** [comment]
We use Java 9 and use this lib for checking if Tiff has premultiplied transperancy or not. Now we are using master snapshot with fixes for Java 9, I will check with release candidate today.

**Comment by Jugen** [comment]
Release candidate works with Java **10** accessing jpeg2000 images :-)

**Comment by stain** [comment]
Thanks for checking, folks! I can let it rest till Monday if you need time for testing. Would be silly if we need to roll a 1.4.1 right away..

@ansell you are right in that PNG will be done by the JDK's provider, but good to know compile/test works in Java 9.

@Jugen I have not prepared a corresponding release candidate for jai-imageio-jpeg2000 yet (would appreciate help with some [outstanding pull requests](https://github.com/jai-imageio/jai-imageio-jpeg2000/pulls) there).

 Do you mean you used the older jai-imageio-jpeg2000 with the newer jai-imageio-core?

**Comment by Jugen** [comment]
Yes, I used jai-imageio-jpeg2000 1.3.0 with core rc 1.4.0
One of those PR's is mine, how can I help ?

**Comment by mykolap** [comment]
rc 1.4.0 works fine for me (java 9, we use it only for images with tiff format)

**Comment by stain** [comment]
@Jugen, perhaps just have a look on jai-imageio-jpeg2000 if the Travis tests can be fixed? Travis fails on your PR jai-imageio/jai-imageio-jpeg2000#24, but it might be related to changes in Travis.

You can upgrade the dependency to the RC 1.4.0 by using the pom.xml snippets from https://github.com/jai-imageio/jai-imageio-core/releases/tag/jai-imageio-core-1.4.0

**Comment by stain** [comment]
Thanks, @mykolap - can you check that you are not accidentally testing with the java.desktop-provided TIFF reader? See https://github.com/jai-imageio/jai-imageio-core/blob/master/src/test/java/com/github/jaiimageio/TiffTest.java#L137 (of course equivalent for Reader then)

**Comment by stain** [comment]
thanks for checking, @JamzTheMan! I'm pushing the Maven Central button then :)

**Comment by stain** [comment]
jai-imageio-core 1.4.0 now published to [Maven Central](https://repo.maven.apache.org/maven2/com/github/jai-imageio/jai-imageio-core/) - should appear in a couple of hours after mirroring.

**Comment by stain** [comment]
Official release notes: https://github.com/jai-imageio/jai-imageio-core/releases/tag/jai-imageio-core-1.4.0
Tweet: https://twitter.com/soilandreyes/status/985785864524623872

**Comment by stain** [comment]
Thanks for the help, everyone! I will see if it's easy to do a corresponding jdk9-compatible jai-imageio-jpeg2000 release too.
