### ISSUE TITLE
ConverterTest fails on Java 8: UnsatisfiedLink

### ISSUE THREAD

**Issue by stain** [jai-imageio/jai-imageio-core#6]
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.139 sec <<< FAILURE!
testname(com.sun.media.imageio.ConverterTest)  Time elapsed: 0.11 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Ljava/lang/Class;Ljava/lang/Class;)V
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.<clinit>(JPEGImageWriter.java:186)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:96)
	at javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:843)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:827)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1596)
	at javax.imageio.ImageIO.write(ImageIO.java:1520)
	at com.sun.media.imageio.ConverterTest.testname(ConverterTest.java:25)


Results :

Tests in error: 
  ConverterTest.testname:25 » UnsatisfiedLink com.sun.imageio.plugins.jpeg.JPEGI...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by kmxz** [comment]
I found the whole thing does not work under Java 8. Now I downgraded to Java 7 to use this repository.

**Comment by stain** [comment]
Yes, I am not sure why, I believe it worked under earlier Open JDK 8 last
year. Obviously the java.net guys have linked to something JVM internal
that has since changed.

Quite important to fix as Java 7 is facing end of life in a few months!

BTW - Did you notice I moved to github.com/jai-imageio? Its in preparation
for the Maven Central build - we need a neutral/new groupId - perhaps
com.github.jai-imageio?

**Comment by stain** [comment]
Verified to still be a bug with Oracle JDK 8u31-linux.x64 on Ubuntu 14.10.

**Comment by stain** [comment]
So the bug is in the built-in JPEG support, not in the additional files from `jai-imageio-core`. The `ConverterTest` just tries to instantiate all of them.. A workaround is to skip the JPEG test.

**Comment by stain** [comment]
This test doesn't fail in Centos 7/x64 (Docker) using  Oracle jdk-8u31-linux-x64.rpm
So the linkage error is probably a `.so` kind of linking error (`initWriterIDs` is a native method) - probably not too unrelated to other `libjpeg` issues with OpenJDK.

**Comment by stain** [comment]
Retesting with Oracle JDK 8 on Ubuntu 14.10 seems to also work. I must have messed up my `JAVA_HOME` earlier.. so it's a problem with OpenJDK 8 and libjpeg not having the `initWriterIDs` method in Ubuntu 14.10.

Oracle's version works because they have their own `libjpeg.so`

I suggest to skip the test with us, and report this upstream to debian-java.

**Comment by stain** [comment]
OK, I have worked around by skipping JPEG tests (it's not the `jai-imageio` code anyway being tested there). I'll close this issue and make a new one as a reminder to tell Debian.

**Comment by stain** [comment]
Also fixed `pom.xml` so that doclint thing comes in automatically for javadoc.

**Comment by stain** [comment]
Tracked in Debian as https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1421501
