### ISSUE TITLE
(PNM) ASCII write .ppm files fails.

### ISSUE THREAD

**Issue by peterhull90** [jai-imageio/jai-imageio-core#7]
If I create a BufferedImage with TYPE_INT_RGB I can save a 'raw' ppm but not an ASCII one using the PNM ImageWriter. I get:
```
java.lang.ClassCastException: java.awt.image.SinglePixelPackedSampleModel cannot be cast to java.awt.image.ComponentSampleModel
	at com.sun.media.imageioimpl.plugins.pnm.PNMImageWriter.write(PNMImageWriter.java:582) 
```
The offending line:
```java
int[] bandOffset =
    ((ComponentSampleModel)sampleModel).getBandOffsets();
```
Now, the variable `bandOffset` is not actually used, and, comparing the equivalent code for a raw write, that line is missing (line 640 in the same file). Therefore I believe that line can simply be deleted.

I know this project is no longer under development but this seems a straightforward fix. I will submit a pull request shortly.

**Comment by stain** [comment]
Fixed in #8 - thanks to @peterhull90.

The project (or at least our fork of it) is under development as long as anyone contributes  - this is why I made a new GitHub organization. :-)
