### ISSUE TITLE
Release in Maven Central repository?

### ISSUE THREAD

**Issue by stain** [jai-imageio/jai-imageio-core#9]
.. and avoid users to depend on http://www.mygrid.org.uk/maven/repository/

Sonatype's `pom.xml` requirements for going into Central might require some more metadata:
 http://central.sonatype.org/pages/requirements.html

..we  would presumably need a new `<groupId>` as we are not really `net.java.dev.jai-imageio`.
Perhaps just `<groupId>com.github.jai-imageio</groupId>` ? (are dashes allowed here?) Views?

I'm not proposing to change the Java package name (yet), so that would remain as `com.sun.media.imageio` for now... although that is probably next on the list :-) And then version numbers!

**Comment by jvtrigueros** [comment]
:+1:

**Comment by stain** [comment]
I've prepared the pom and requested the groupId https://issues.sonatype.org/browse/OSSRH-14163

**Comment by stain** [comment]
Both 1.2.1 and 1.3.0 (now with new package names) are pushed to bintray (See https://github.com/jai-imageio/jai-imageio-core#usage ) -- they should appear in Maven Central in a few days (and thus no longer need a custom `<repository>`

**Comment by jvtrigueros** [comment]
This is awesome! Thanks @stain!

**Comment by stain** [comment]
Now pushed to Central - it should appear tomorrow.

**Comment by stain** [comment]
Browse at https://oss.sonatype.org/content/repositories/releases/com/github/jai-imageio/ - should be on
http://central.maven.org/maven2/com/github/jai-imageio should be there tomorrow
